### ISSUE TITLE
No such file or directory.common

### ISSUE THREAD

**Issue by yardern** [rmoesbergen/openwrt-ha-device-tracker#34]
Thank @rmoesbergen for this great software!

I followed until:
run 'service presence-detector enable' to enable the service at startup

But I got:
No such file or directory.common

The only changes I made are:

**_"interfaces": ["hostapd.wlan0", "hostapd.wlan0-1", "hostapd.wlan1"],
  "filter_is_denylist": false,
  "filter": ["AA:AA:AA:AA:AA:AA", "BB:BB:BB:BB:BB:BB", "CC:CC:CC:CC:CC:CC"],
  "params": {
    "AA:AA:AA:AA:AA:AA": {"host_name": "Device A"},
	"BB:BB:BB:BB:BB:BB": {"host_name": "Device B"},
	"CC:CC:CC:CC:CC:CC": {"host_name": "Device C"}
  },_**

Have I got the format for multiple devices correct? What am I doing wrong please?

Thanks.

**Comment by rmoesbergen** [comment]
Hi @yardern , your config looks fine (be sure to lower-case the mac addresses though). I think the problem you're seeing is because your init script has the wrong line-endings. Did you create it in windows and upload it to your router? If so, the line endings will probably be CRLF where it should be LF (unix-style). Try to create the files with an editor on the device (or copy-paste).

See also: https://stackoverflow.com/questions/73799370/no-such-file-or-directory-common

**Comment by yardern** [comment]
Thank you! @rmoesbergen, that is exact the reason.
I used Notepad++ in Windows. After a little Googling, I found that Notepad++ can do the CRLF to LF conversion.
Thank you again!
